version: '3'
services:
  grafana:
    image: grafana/grafana:1.0
    build: ./grafana/.
    ports:
      - '3000:3000'
    command: [ "-s" ]
    depends_on:
      - influxdb
  fluentd:
    image: fluentd/fluentd:1.0
    build: ./fluentd/.
    user: 'fluent'
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./data/fluentd/log:/fluentd/log
    command: [ "-s" ]
  influxdb:
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=grafana
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=grafana
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - './data/influxdb/data:/var/lib/influxdb'
